const String login = 'login';
const String home = 'home';
const String GET_CATEGORIES = 'categories';
const String FAVOURITES = 'favorites';
const String PROFILE = 'profile';
const String REGISTER = 'register';
const String UPDATE = 'update-profile';
const String SEARCH = 'products/search';
const String CATEGORY_CONTENT = 'products?category_id=';
